# Generated by Django 4.0.4 on 2022-05-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.FloatField(max_length=100)),
                ('last_evaluation_rating', models.FloatField(max_length=100)),
                ('projects_worked_on', models.IntegerField(max_length=100)),
                ('average_montly_hours', models.IntegerField(max_length=200)),
                ('time_spend_company', models.IntegerField(max_length=200)),
                ('work_accident', models.IntegerField(max_length=100)),
                ('promotion_last_5years', models.IntegerField(max_length=200)),
                ('department', models.CharField(max_length=300)),
                ('salary', models.CharField(max_length=100)),
                ('attrition', models.IntegerField()),
            ],
        ),
    ]
